/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        // Open Color palette integration
        gray: {
          0: "var(--oc-gray-0)",
          1: "var(--oc-gray-1)",
          2: "var(--oc-gray-2)",
          3: "var(--oc-gray-3)",
          4: "var(--oc-gray-4)",
          5: "var(--oc-gray-5)",
          6: "var(--oc-gray-6)",
          7: "var(--oc-gray-7)",
          8: "var(--oc-gray-8)",
          9: "var(--oc-gray-9)",
        },
        red: {
          0: "var(--oc-red-0)",
          1: "var(--oc-red-1)",
          2: "var(--oc-red-2)",
          3: "var(--oc-red-3)",
          4: "var(--oc-red-4)",
          5: "var(--oc-red-5)",
          6: "var(--oc-red-6)",
          7: "var(--oc-red-7)",
          8: "var(--oc-red-8)",
          9: "var(--oc-red-9)",
        },
        orange: {
          0: "var(--oc-orange-0)",
          1: "var(--oc-orange-1)",
          2: "var(--oc-orange-2)",
          3: "var(--oc-orange-3)",
          4: "var(--oc-orange-4)",
          5: "var(--oc-orange-5)",
          6: "var(--oc-orange-6)",
          7: "var(--oc-orange-7)",
          8: "var(--oc-orange-8)",
          9: "var(--oc-orange-9)",
        },
        yellow: {
          0: "var(--oc-yellow-0)",
          1: "var(--oc-yellow-1)",
          2: "var(--oc-yellow-2)",
          3: "var(--oc-yellow-3)",
          4: "var(--oc-yellow-4)",
          5: "var(--oc-yellow-5)",
          6: "var(--oc-yellow-6)",
          7: "var(--oc-yellow-7)",
          8: "var(--oc-yellow-8)",
          9: "var(--oc-yellow-9)",
        },
        green: {
          0: "var(--oc-green-0)",
          1: "var(--oc-green-1)",
          2: "var(--oc-green-2)",
          3: "var(--oc-green-3)",
          4: "var(--oc-green-4)",
          5: "var(--oc-green-5)",
          6: "var(--oc-green-6)",
          7: "var(--oc-green-7)",
          8: "var(--oc-green-8)",
          9: "var(--oc-green-9)",
        },
        blue: {
          0: "var(--oc-blue-0)",
          1: "var(--oc-blue-1)",
          2: "var(--oc-blue-2)",
          3: "var(--oc-blue-3)",
          4: "var(--oc-blue-4)",
          5: "var(--oc-blue-5)",
          6: "var(--oc-blue-6)",
          7: "var(--oc-blue-7)",
          8: "var(--oc-blue-8)",
          9: "var(--oc-blue-9)",
        },
        indigo: {
          0: "var(--oc-indigo-0)",
          1: "var(--oc-indigo-1)",
          2: "var(--oc-indigo-2)",
          3: "var(--oc-indigo-3)",
          4: "var(--oc-indigo-4)",
          5: "var(--oc-indigo-5)",
          6: "var(--oc-indigo-6)",
          7: "var(--oc-indigo-7)",
          8: "var(--oc-indigo-8)",
          9: "var(--oc-indigo-9)",
        },
        violet: {
          0: "var(--oc-violet-0)",
          1: "var(--oc-violet-1)",
          2: "var(--oc-violet-2)",
          3: "var(--oc-violet-3)",
          4: "var(--oc-violet-4)",
          5: "var(--oc-violet-5)",
          6: "var(--oc-violet-6)",
          7: "var(--oc-violet-7)",
          8: "var(--oc-violet-8)",
          9: "var(--oc-violet-9)",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
