services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - PORT=8080
      - MONGODB_URI=mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@mongo:27017/excalidraw
      - DB_NAME=excalidraw
      - JWT_SECRET=${EXCALIDRAW_JWT_SECRET}
    networks:
      - dokploy-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.ex-backend.rule=Host(`exd.backend.drshnk.com`) && PathPrefix(`/api`)
      - traefik.http.routers.ex-backend.entrypoints=websecure
      - traefik.http.routers.ex-backend.tls.certResolver=letsencrypt
      - traefik.http.services.ex-backend.loadbalancer.server.port=8080

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
      args:
        - VITE_APP_BACKEND_URL=${EXCALIDRAW_BACKEND_URL:-https://exd.backend.drshnk.com/api}
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - dokploy-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.ex-frontend.rule=Host(`exd.drshnk.com`)
      - traefik.http.routers.ex-frontend.entrypoints=websecure
      - traefik.http.routers.ex-frontend.tls.certResolver=letsencrypt
      - traefik.http.services.ex-frontend.loadbalancer.server.port=80

networks:
  dokploy-network:
    external: true
