# .air.toml
# Config file for Air - https://github.com/air-verse/air

root = "."
tmp_dir = "tmp"

[build]
  # Command to build the Go app
  cmd = "go build -buildvcs=false -o ./tmp/main ./cmd/api"
  # Binary to run
  bin = "./tmp/main"
  # Folders to watch for changes
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["tmp", "vendor"]
  # Log name
  log = "air_errors.log"

[log]
  # Show log time
  time = true

[misc]
  # Delete tmp directory on exit
  clean_on_exit = true
